# Generated by Django 2.2.1 on 2019-06-04 16:17

import core.fields
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', core.fields.UUIDPrimaryKey(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('withdrawn', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_history', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=list, size=None)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish')], db_index=True, max_length=15)),
                ('accepted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='proposals.ProposalAuthor')),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', core.fields.UUIDPrimaryKey(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('decision', models.PositiveSmallIntegerField(choices=[(2, 'Yes'), (0, 'Skip'), (1, 'No')], db_index=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='proposals.Proposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'proposal')},
            },
        ),
    ]
